/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.cruzeirodosul.certificadora.action;

import br.edu.cruzeirodosul.certificadora.util.CertificacaoUSB;
import br.edu.cruzeirodosul.util.commons.format.StringFormatUtil;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Administrador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static TelaPrincipal telaPrincipal;
    private DefaultTableModel dtm = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        carregaDados();
        initComponents();
        btnCertificar.setEnabled(false);
        try {
            MaskFormatter dateMaskInicio = new MaskFormatter("##/##/####");
            dateMaskInicio.install(inputDtInicio);
            dateMaskInicio.install(inputDtFinal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível criar formatação para os campos de datas!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDados = new javax.swing.JPanel();
        labelEmpresa = new javax.swing.JLabel();
        cbxEmpresa = new javax.swing.JComboBox<>();
        labelDtInicio = new javax.swing.JLabel();
        inputDtInicio = new javax.swing.JFormattedTextField();
        labelDtFinal = new javax.swing.JLabel();
        inputDtFinal = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        panelDocumentos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocumentos = new javax.swing.JTable();
        btnCertificar = new javax.swing.JButton();
        lableTotalArquivo = new javax.swing.JLabel();
        txtTotalArquivo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaLogs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        labelEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelEmpresa.setText("Empresa:");

        cbxEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        labelDtInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDtInicio.setText("Data Inicial:");

        labelDtFinal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDtFinal.setText("Data Final:");

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
                panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDtInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDtFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDadosLayout.setVerticalGroup(
                panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelEmpresa)
                                .addComponent(cbxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDtInicio)
                                .addComponent(labelDtFinal)
                                .addComponent(inputDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar)
                                .addComponent(btnSair))
                        .addContainerGap(12, Short.MAX_VALUE))
        );

        panelDocumentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Documentos"));

        tblDocumentos.setModel(dtm);
        jScrollPane1.setViewportView(tblDocumentos);

        btnCertificar.setText("Certificar Arquivo");
        btnCertificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCertificarMouseClicked(evt);
            }
        });
        btnCertificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDocumentosLayout = new javax.swing.GroupLayout(panelDocumentos);
        panelDocumentos.setLayout(panelDocumentosLayout);
        panelDocumentosLayout.setHorizontalGroup(
                panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDocumentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDocumentosLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCertificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
        );
        panelDocumentosLayout.setVerticalGroup(
                panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDocumentosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCertificar)
                        .addGap(102, 102, 102))
        );

        lableTotalArquivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lableTotalArquivo.setText("Total Arquivo:");

        txtTotalArquivo.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs de Processamento"));

        txtAreaLogs.setColumns(20);
        txtAreaLogs.setRows(5);
        jScrollPane3.setViewportView(txtAreaLogs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(lableTotalArquivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotalArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lableTotalArquivo)
                                .addComponent(txtTotalArquivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCertificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCertificarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCertificarMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        adicionarLinhas();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnCertificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificarActionPerformed
        // TODO add your handling code here:
        try {
            JPanel panel = new JPanel();
            JLabel label = new JLabel("Digite a senha do certificado");
            JPasswordField pass = new JPasswordField(10);
            panel.add(label);
            panel.add(pass);
            String[] options = new String[]{"OK", "Cancelar"};
            int option = JOptionPane.showOptionDialog(null, panel, "Atenção",
                    JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[1]);
            if (option == 0) {
                if (!StringFormatUtil.isNull(pass.getText())) {
                    int totalLinhas = dtm.getRowCount();
                    txtAreaLogs.setText(txtAreaLogs.getText() + "[" + (new SimpleDateFormat("dd/MM/YYYY HH:mm:ss").format(new Date())) + "] - Iniciando a certificação de " + txtTotalArquivo.getText() + "arquivos. \n");
                    txtAreaLogs.update(txtAreaLogs.getGraphics());
                    for (int i = 0; i < totalLinhas; i++) {
                        txtAreaLogs.setText(txtAreaLogs.getText() + "[" + (new SimpleDateFormat("dd/MM/YYYY HH:mm:ss").format(new Date())) + "] - Tentando Certificar arquivo: " + dtm.getValueAt(i, 3) + "\n");
                        txtAreaLogs.update(txtAreaLogs.getGraphics());
                        System.out.println("tentando certificar o arquivo " + dtm.getValueAt(i, 3) + "");
                        try {
                            if (CertificacaoUSB.processar(dtm.getValueAt(i, 3).toString(), dtm.getValueAt(i, 3).toString().replace(".pdf", "_certificado.pdf"), pass.getText())) {
                                txtAreaLogs.setText(txtAreaLogs.getText() + "[" + (new SimpleDateFormat("dd/MM/YYYY HH:mm:ss").format(new Date())) + "] - Arquivo " + dtm.getValueAt(i, 3) + " certificado com sucesso!" + "\n");
                                txtAreaLogs.update(txtAreaLogs.getGraphics());
//JOptionPane.showMessageDialog(null, "Arquivos certificados com sucesso!!");
                            }

                        } catch (IOException e) {
                            txtAreaLogs.setText(txtAreaLogs.getText() + "[" + (new SimpleDateFormat("dd/MM/YYYY HH:mm:ss").format(new Date())) + "] - Ocorreu um erro ao tentar certificar o arquivo: " + dtm.getValueAt(i, 3) + " - Detalhe: " + e + " \n");
                            txtAreaLogs.update(txtAreaLogs.getGraphics());
                        }
                    }

                    txtAreaLogs.setText(txtAreaLogs.getText() + "[" + (new SimpleDateFormat("dd/MM/YYYY HH:mm:ss").format(new Date())) + "] - Certificação finalizada! \n");
                    txtAreaLogs.update(txtAreaLogs.getGraphics());

                } else {
                    JOptionPane.showMessageDialog(null, "Deve informar a senha do certificado!");
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível executar operação. Detalhes: " + e);
        }
    }//GEN-LAST:event_btnCertificarActionPerformed

    private void carregaDados() {
        String header[] = new String[]{"Cód. Inst.", "Rgm", "Aluno", "Arquivo", "ID Arquivo"};
        dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(header);

    }

    private void adicionarLinhas() {

        dtm.addRow(new Object[]{"data1", "data2", "data3", "C:\\IAIK_CMS.pdf", "data5"});
        dtm.addRow(new Object[]{"data1", "data2", "data3", "C:\\test.pdf", "data5"});

        txtTotalArquivo.setText(dtm.getRowCount() + "");
        btnCertificar.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telaPrincipal = new TelaPrincipal();
                telaPrincipal.setVisible(true);
                telaPrincipal.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCertificar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxEmpresa;
    private javax.swing.JFormattedTextField inputDtFinal;
    private javax.swing.JFormattedTextField inputDtInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDtFinal;
    private javax.swing.JLabel labelDtInicio;
    private javax.swing.JLabel labelEmpresa;
    private javax.swing.JLabel lableTotalArquivo;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelDocumentos;
    private javax.swing.JTable tblDocumentos;
    private javax.swing.JTextArea txtAreaLogs;
    private javax.swing.JLabel txtTotalArquivo;
    // End of variables declaration//GEN-END:variables
}
